//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// curve_editor.rc で使用
//
#define IDD_ABOUT                       128
#define IDD_PREF                        129
#define IDD_PREF_APPEARANCE             130
#define IDD_PREF_BEHAVIOR               131
#define IDD_PREF_EDITING                132
#define IDD_PREF_GENERAL                133
#define IDD_WARNING_AUTOSAVER           134
#define IDD_BEZIER_PARAM                135
#define IDD_MODIFIER_DISCRETIZATION     136
#define IDD_ID_JUMPTO                   137
#define IDD_CURVE_CODE                  138
#define IDD_MODIFIER                    139
#define IDD_MODIFIER_NOISER             153
#define IDB_COPY                        256
#define IDB_READ                        257
#define IDB_SAVE                        258
#define IDB_CLEAR                       259
#define IDB_FIT                         260
#define IDB_MORE                        261
#define IDB_BACK                        262
#define IDB_NEXT                        263
#define IDR_MENU_MORE                   384
#define IDR_MENU_CURVE                  385
#define IDR_MENU_GRAPH                  386
#define IDR_MENU_ID                     387
#define IDR_MENU_BEZIER_HANDLE          388
#define IDC_DRAG                        512
#define IDC_BUTTON_APPLY                768
#define IDC_BUTTON_RESET                769
#define IDC_BUTTON_CURVE_COLOR          770
#define IDC_BUTTON_BACKGROUND_IMAGE     771
#define IDC_BUTTON_ADD                  772
#define IDC_BUTTON_EDIT                 773
#define IDC_BUTTON_UP                   774
#define IDC_BUTTON_DOWN                 775
#define IDC_BUTTON_REMOVE               776
#define IDC_BUTTON_RENAME               777
#define IDC_CHECK_REVERSE_WHEEL         1024
#define IDC_CHECK_AUTO_COPY             1025
#define IDC_CHECK_AUTO_APPLY            1026
#define IDC_CHECK_DONTSHOWAGAIN         1027
#define IDC_CHECK_NOTIFY_UPDATE         1028
#define IDC_CHECK_SHOW_POPUP            1029
#define IDC_CHECK_ENABLE_HOTKEYS        1030
#define IDC_CHECK_SHOW_TRACE            1031
#define IDC_CHECK_BACKGROUND_IMAGE      1032
#define IDC_COMBO_LANGUAGE              1280
#define IDC_COMBO_THEME                 1281
#define IDC_COMBO_GRAPHIC_METHOD        1282
#define IDC_EDIT_CURVE_CODE             1408
#define IDC_EDIT_BEZIER_PARAM           1409
#define IDC_EDIT_BACKGROUND_IMAGE       1410
#define IDC_LIST_CATEGORY               1536
#define IDC_LIST_MODIFIER               1537
#define IDC_SLIDER_CURVE_THICKNESS      1664
#define IDC_SLIDER_CURVE_DRAWING_INTERVAL 1665
#define IDC_SLIDER_SAMPLING             1666
#define IDC_SLIDER_QUANTIZATION         1667
#define IDC_SLIDER_IMAGE_OPACITY        1668
#define IDC_STATIC_CURVE_THICKNESS      1669
#define IDC_STATIC_CURVE_DRAWING_INTERVAL 1670
#define IDC_STATIC_SAMPLING             1671
#define IDC_STATIC_QUANTIZATION         1672
#define IDC_STATIC_PLUGIN_INFO          1673
#define IDC_STATIC_BACKGROUND_IMAGE     1674
#define IDC_STATIC_IMAGE_PATH           1675
#define IDC_STATIC_BACKGROUND_IMAGE2    1676
#define IDC_STATIC_IMAGE_OPACITY        1677
#define IDC_SYSLINK_ABOUT               1792
#define IDS_ERROR_LUA_NOT_FOUND         4096
#define IDS_ERROR_EXEDIT_NOT_FOUND      4097
#define IDS_ERROR_EXEDIT_HOOK_FAILED    4098
#define IDS_ERROR_GRAPHICS_INIT_FAILED  4099
#define IDS_ERROR_CONNECTION_FAILED     4100
#define IDS_ERROR_INVALID_INPUT         4101
#define IDS_ERROR_OUT_OF_RANGE          4102
#define IDS_ERROR_CODE_COPY_FAILED      4103
#define IDS_ERROR_DATA_LOAD_FAILED      4104
#define IDS_WARNING_DELETE_CURVE        5120
#define IDS_WARNING_DELETE_ALL_CURVES   5121
#define IDS_WARNING_AUTOSAVER_NOT_FOUND 5122
#define IDS_WARNING_PREF_RESET          5122
#define IDS_WARNING_DELETE_ID           5123
#define IDS_WARNING_DELETE_ALL_IDS      5124
#define IDS_WARNING_REMOVE_MODIFIER     5125
#define IDS_INFO_LATEST_VERSION         6144
#define IDS_INFO_UPDATE_AVAILABLE       6145
#define IDS_INFO_RESTART_AVIUTL         6146
#define IDS_LABEL_EDIT_MODE_NORMAL      7168
#define IDS_LABEL_EDIT_MODE_VALUE       7169
#define IDS_LABEL_EDIT_MODE_BEZIER      7170
#define IDS_LABEL_EDIT_MODE_ELASTIC     7171
#define IDS_LABEL_EDIT_MODE_BOUNCE      7172
#define IDS_LABEL_EDIT_MODE_SCRIPT      7173
#define IDS_LABEL_CURVE_SEGMENT_TYPE_LINEAR 7175
#define IDS_LABEL_TOOLTIP_COPY          7176
#define IDS_LABEL_TOOLTIP_READ          7177
#define IDS_LABEL_TOOLTIP_SAVE          7178
#define IDS_LABEL_TOOLTIP_CLEAR         7179
#define IDS_LABEL_TOOLTIP_FIT           7180
#define IDS_LABEL_TOOLTIP_MORE          7181
#define IDS_LABEL_TOOLTIP_ID_BACK       7182
#define IDS_LABEL_TOOLTIP_ID_NEXT       7183
#define IDS_LABEL_TOOLTIP_CURRENT_ID    7184
#define IDS_LABEL_APPLY_MODE_NORMAL     7296
#define IDS_LABEL_APPLY_MODE_IGNORE_MIDPOINT 7297
#define IDS_LABEL_APPLY_MODE_INTERPOLATE 7298
#define IDS_LABEL_PREFERENCE_GENERAL    7424
#define IDS_LABEL_PREFERENCE_APPEARANCE 7425
#define IDS_LABEL_PREFERENCE_BEHAVIOR   7426
#define IDS_LABEL_PREFERENCE_EDITING    7427
#define IDS_LABEL_MENU_UPDATE_AVAILABLE 7680
#define IDS_LABEL_THEME_NAME_DARK       7936
#define IDS_LABEL_THEME_LIGHT           7937
#define IDS_LABEL_THEME_NAME_LIGHT      7937
#define IDS_LABEL_SELECT_BG_IMAGE       8064
#define IDS_LABEL_MODIFIER_DISCRETIZER  8192
#define IDS_LABEL_MODIFIER_NOISER       8193
#define IDS_WORD_VERSION                9216
#define IDS_WORD_EDIT_MODE              9217
#define IDS_WORD_LANGUAGE_AUTOMATIC     9218
#define IDS_WORD_IMAGE_FILES            9219
#define ID_EDIT_APPLYMODE               40060
#define ID_GRAPH_ALIGN                  40092
#define ID_GRAPH_REVERSE                40095
#define ID_GRAPH_FIT                    40097
#define ID_MORE                         40108
#define ID_MORE_WINDOWLAYOUT            40109
#define ID_MORE_SHOWLIBRARY             40112
#define ID_MORE_PREFERENCES             40113
#define ID_MORE_HELP                    40114
#define ID_MORE_CHECKFORUPDATES         40116
#define ID_MORE_REPORTABUG              40117
#define ID_LAYOUT_VERTICAL              40118
#define ID_LAYOUT_HORIZONTAL            40119
#define ID_MORE_ABOUT                   40120
#define ID_MORE_UPDATES                 40121
#define ID_CURVE_TYPE                   40124
#define ID_CURVE_REVERSE                40125
#define ID_GRAPH_VELOCITY               40127
#define ID_GRAPH_SHOWHANDLE             40129
#define ID_GRAPH_APPLYMODE              40133
#define ID_CURVE_COPY                   40138
#define ID_CURVE_PASTE                  40139
#define ID_MANIFEST_VISUALSTYLE         40142
#define ID_CURVE_MODIFIER               40143
#define ID_GRAPH_MODIFIER               40147
#define ID_ID_JUMP                      40151
#define ID_ID_DELETE                    40153
#define ID_ID_JUMPTOFIRST               40155
#define ID_ID_JUMPTOLAST                40156
#define ID_BEZIER_HANDLE_ROTATE         40159
#define ID_BEZIER_HANDLE_ROOT           40161
#define ID_ID_DELETE_ALL                40163

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        155
#define _APS_NEXT_COMMAND_VALUE         40167
#define _APS_NEXT_CONTROL_VALUE         1048
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
