//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// curve_editor.rc で使用
//
#define IDD_PREF_APPEARANCE             103
#define IDD_PREF                        104
#define IDD_PREF_BEHAVIOR               105
#define IDD_PREF_EDITING                106
#define IDR_MENU_GRAPH                  111
#define IDD_WARNING_AUTOSAVER           114
#define IDD_PREF_GENERAL                115
#define IDB_READ                        117
#define IDB_SAVE                        118
#define IDB_CLEAR                       119
#define IDB_FIT                         120
#define IDB_MORE                        121
#define IDB_BACK                        123
#define IDB_NEXT                        124
#define IDR_MENU_MORE                   125
#define IDR_MENU_CURVE                  126
#define IDD_CURVE_CODE                  128
#define IDC_DRAG                        132
#define IDD_ABOUT                       135
#define IDD_BEZIER_PARAM                136
#define IDD_CURVE_DISCRETIZATION        139
#define IDD_CURVE_CODE1                 140
#define IDD_ID_JUMPTO                   140
#define IDR_MENU_ID                     141
#define IDR_MENU_BEZIER_HANDLE          146
#define IDC_BUTTON_APPLY                1003
#define IDC_BUTTON_RESET                1004
#define IDC_COMBO_LANGUAGE              1005
#define IDC_BUTTON1                     1006
#define IDB_COPY                        1006
#define IDC_BUTTON_CURVE_COLOR          1006
#define IDC_CHECK1                      1007
#define IDC_CHECK_REVERSE_WHEEL         1007
#define IDC_CHECK2                      1008
#define IDC_CHECK_AUTO_COPY             1008
#define IDC_DONTSHOWAGAIN               1009
#define IDC_LIST_CATEGORY               1009
#define IDC_CHECK_NOTIFY_UPDATE         1010
#define IDC_CHECK_SHOW_POPUP            1011
#define IDC_TREE1                       1012
#define IDC_CHECK_HOTKEY                1012
#define IDC_CHECK_ENABLE_HOTKEYS        1012
#define IDC_EDIT_CURVE_CODE             1016
#define IDC_COMBO_THEME                 1017
#define IDC_CHECK_AUTO_APPLY            1018
#define IDC_SLIDER_CURVE_THICKNESS      1020
#define IDC_SLIDER_CURVE_DRAWING_INTERVAL 1021
#define IDC_COMMAND1                    1023
#define IDC_CHECK_SHOW_TRACE            1024
#define IDC_STATIC_IMAGE_OPACITY        1024
#define IDC_STATIC_CURVE_DRAWING_INTERVAL 1026
#define IDC_COMBO_GRAPHIC_METHOD        1027
#define IDC_STATIC_PLUGIN_INFO          1030
#define IDC_CHECK_BACKGROUND_IMAGE      1038
#define IDC_EDIT_BEZIER_PARAM           1032
#define IDC_BUTTON_BACKGROUND_IMAGE     1040
#define IDC_STATIC_BACKGROUND_IMAGE     1041
#define IDC_STATIC_IMAGE_PATH           1041
#define IDC_STATIC_BACKGROUND_IMAGE2    1042
#define IDC_STATIC_QUANTIZATION         1036
#define IDC_EDIT1                       1037
#define IDS_ERROR_LUA_NOT_FOUND         4096
#define IDS_ERROR_EXEDIT_NOT_FOUND      4097
#define IDS_ERROR_EXEDIT_HOOK_FAILED    4098
#define IDS_ERROR_GRAPHICS_INIT_FAILED  4099
#define IDS_ERROR_CONNECTION_FAILED     4100
#define IDS_ERROR_INVALID_INPUT         4101
#define IDS_ERROR_OUT_OF_RANGE          4102
#define IDS_ERROR_CODE_COPY_FAILED      4103
#define IDS_ERROR_DATA_LOAD_FAILED      4104
#define IDS_WARNING_DELETE_CURVE        5120
#define IDS_WARNING_DELETE_ALL_CURVES   5121
#define IDS_WARNING_AUTOSAVER_NOT_FOUND 5122
#define IDS_WARNING_PREF_RESET          5122
#define IDS_WARNING_DELETE_ID           5123
#define IDS_WARNING_DELETE_ALL_IDS      5124
#define IDS_INFO_LATEST_VERSION         6144
#define IDS_INFO_UPDATE_AVAILABLE       6145
#define IDS_INFO_RESTART_AVIUTL         6146
#define IDS_LABEL_EDIT_MODE_NORMAL      7168
#define IDS_LABEL_EDIT_MODE_VALUE       7169
#define IDS_LABEL_EDIT_MODE_BEZIER      7170
#define IDS_LABEL_EDIT_MODE_ELASTIC     7171
#define IDS_LABEL_EDIT_MODE_BOUNCE      7172
#define IDS_LABEL_EDIT_MODE_SCRIPT      7173
#define IDS_LABEL_CURVE_SEGMENT_TYPE_LINEAR 7175
#define IDS_LABEL_TOOLTIP_COPY          7176
#define IDS_LABEL_TOOLTIP_READ          7177
#define IDS_LABEL_TOOLTIP_SAVE          7178
#define IDS_LABEL_TOOLTIP_CLEAR         7179
#define IDS_LABEL_TOOLTIP_FIT           7180
#define IDS_LABEL_TOOLTIP_MORE          7181
#define IDS_LABEL_TOOLTIP_ID_BACK       7182
#define IDS_LABEL_TOOLTIP_ID_NEXT       7183
#define IDS_LABEL_TOOLTIP_CURRENT_ID    7184
#define IDS_LABEL_PREFERENCE_GENERAL    7424
#define IDS_LABEL_PREFERENCE_APPEARANCE 7425
#define IDS_LABEL_PREFERENCE_BEHAVIOR   7426
#define IDS_LABEL_PREFERENCE_EDITING    7427
#define IDS_LABEL_MENU_UPDATE_AVAILABLE 7680
#define IDS_LABEL_THEME_NAME_DARK       7936
#define IDS_LABEL_THEME_LIGHT           7937
#define IDS_LABEL_THEME_NAME_LIGHT      7937
#define IDS_LABEL_SELECT_BG_IMAGE       8064
#define IDS_WORD_VERSION                9216
#define IDS_WORD_EDIT_MODE              9217
#define IDS_WORD_LANGUAGE_AUTOMATIC     9218
#define IDS_WORD_IMAGE_FILES            9219
#define ID_EDIT_APPLYMODE               40060
#define ID_GRAPH_ALIGN                  40092
#define ID_GRAPH_REVERSE                40095
#define ID_GRAPH_FIT                    40097
#define ID_MORE                         40108
#define ID_MORE_WINDOWLAYOUT            40109
#define ID_MORE_SHOWLIBRARY             40112
#define ID_MORE_PREFERENCES             40113
#define ID_MORE_HELP                    40114
#define ID_MORE_CHECKFORUPDATES         40116
#define ID_MORE_REPORTABUG              40117
#define ID_LAYOUT_VERTICAL              40118
#define ID_LAYOUT_HORIZONTAL            40119
#define ID_MORE_ABOUT                   40120
#define ID_MORE_UPDATES                 40121
#define ID_CURVE_TYPE                   40124
#define ID_CURVE_REVERSE                40125
#define ID_GRAPH_VELOCITY               40127
#define ID_GRAPH_SHOWHANDLE             40129
#define ID_GRAPH_APPLYMODE              40133
#define ID_APPLYMODE_NORMAL             40134
#define ID_APPLYMODE_IGNOREMID          40135
#define ID_CURVE_COPY                   40138
#define ID_CURVE_PASTE                  40139
#define ID_MANIFEST_VISUALSTYLE         40142
#define ID_CURVE_DISCRETIZATION         40143
#define ID_GRAPH_DESCRITIZATION         40147
#define ID_ID_JUMP                      40151
#define ID_ID_DELETE                    40153
#define ID_ID_JUMPTOFIRST               40155
#define ID_ID_JUMPTOLAST                40156
#define ID_MENU_40157                   40157
#define ID_MENU_40158                   40158
#define ID_BEZIER_HANDLE_ROTATE         40159
#define ID_BEZIER_HANDLE_               40160
#define ID_BEZIER_HANDLE_ROOT           40161
#define ID_MENU_40162                   40162
#define ID_ID_DELETE_ALL                40163
#define ID_MENU_DELETEALLIDS            40164

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        150
#define _APS_NEXT_COMMAND_VALUE         40165
#define _APS_NEXT_CONTROL_VALUE         1038
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
