#pragma once

#include <string>
#include <Windows.h>



namespace curve_editor::global {
	inline class StringTable {
	public:
		enum class StringId : size_t {
			ErrorLuaDLLNotFound,
			ErrorExeditNotFound,
			ErrorExeditHookFailed,
			ErrorGraphicsInitFailed,
			ErrorConnectionFailed,
			ErrorOutOfRange,
			ErrorInvalidInput,
			ErrorCodeCopyFailed,
			ErrorDataLoadFailed,
			ErrorWebView2InitFailed,
			ErrorCommCtrlInitFailed,
			ErrorPageLoadFailed,
			ErrorPresetCreateFailed,
			WarningDeleteCurve,
			WarningDeleteAllCurves,
			WarningResetPreferences,
			WarningDeleteId,
			WarningDeleteAllIds,
			WarningRemoveModifier,
			WarningRemovePreset,
			WarningRemoveCollection,
			WarningScriptFileNotFound,
			InfoLatestVersion,
			InfoUpdateAvailable,
			InfoRestartAviutl,
			LabelEditModeNormal,
			LabelEditModeValue,
			LabelEditModeBezier,
			LabelEditModeElastic,
			LabelEditModeBounce,
			LabelEditModeScript,
			LabelCurveSegmentTypeLinear,
			LabelApplyModeNormal,
			LabelApplyModeIgnoreMidPoint,
			LabelApplyModeInterpolate,
			LabelTooltipCopy,
			LabelTooltipRead,
			LabelTooltipSave,
			LabelTooltipClear,
			LabelTooltipFit,
			LabelTooltipMore,
			LabelTooltipIdBack,
			LabelTooltipIdNext,
			LabelTooltipCurrentId,
			LabelThemeNameSystem,
			LabelThemeNameDark,
			LabelThemeNameLight,
			LabelPreferenceGeneral,
			LabelPreferenceAppearance,
			LabelPreferenceBehavior,
			LabelPreferenceEditing,
			LabelSelectBackgroundImage,
			LabelSelectCurve,
			LabelModifierDiscretization,
			LabelModifierNoise,
			LabelModifierSineWave,
			LabelModifierSquareWave,
			LabelCollectionNameAll,
			LabelCollectionNameDefault,
			LabelCollectionNameRoot,
			PromptCreatePreset,
			PromptCurveCode,
			PromptCurveParam,
			PromptRenamePreset,
			PromptCreateCollection,
			PromptRenameCollection,
			CaptionCreatePreset,
			CaptionCurveCode,
			CaptionCurveParam,
			CaptionRenamePreset,
			CaptionCreateCollection,
			CaptionRenameCollection,
			CaptionImportCollection,
			CaptionExportCollection,
			WordVersion,
			WordEditMode,
			WordLanguageAutomatic,
			WordImageFiles,
			WordSelect,
			WordCollectionFile,
			MenuGraphApplyMode,
			MenuGraphAddAnchor,
			MenuGraphReverseCurve,
			MenuGraphModifier,
			MenuGraphAlignHandle,
			MenuGraphShowXLabel,
			MenuGraphShowYLabel,
			MenuGraphShowHandle,
			MenuGraphShowVelocityGraph,
			MenuCurveSegmentType,
			MenuCurveSegmentReverse,
			MenuCurveSegmentModifier,
			MenuOthersWindowLayout,
			MenuOthersWindowLayoutVertical,
			MenuOthersWindowLayoutHorizontal,
			MenuOthersExtension,
			MenuOthersExtensionInstall,
			MenuOthersReloadWindow,
			MenuOthersPreferences,
			MenuOthersHelp,
			MenuOthersAbout,
			MenuOthersUpdateAvailable,
			MenuPresetItemRename,
			MenuPresetItemRemove,
			MenuCollectionAddNew,
			MenuCollectionAddImport,
			MenuCollectionRename,
			MenuCollectionRemove,
			MenuCollectionExport,
			MenuBezierHandleRoot,
			MenuBezierHandleAdjustAngle,
			MenuIdxJumpToFirst,
			MenuIdxJumpToLast,
			MenuIdxDelete,
			MenuIdxDeleteAll,
			NumStringId
		};

	private:
		static constexpr size_t MAX_LEN = 0x200;

		std::string string_data[(size_t)StringId::NumStringId];
	public:
		StringTable() noexcept;

		const char* operator[] (StringId str_id);
	} string_table;
} // namespace curve_editor::global