#pragma once

#include <nlohmann/json.hpp>
#include <string>
#include <Windows.h>



namespace curve_editor::global {
	inline class StringTable {
	public:
		enum class StringId : size_t {
			ErrorLuaDLLNotFound,
			ErrorExeditNotFound,
			ErrorExeditHookFailed,
			ErrorOutOfRange,
			ErrorInvalidInput,
			ErrorCodeCopyFailed,
			ErrorDataLoadFailed,
			ErrorWebView2InitFailed,
			ErrorCommCtrlInitFailed,
			ErrorUILoadFailed,
			ErrorPresetCreateFailed,
			ErrorCollectionImportFailed,
			WarningResetCurve,
			WarningResetAllCurves,
			WarningResetPreferences,
			WarningDeleteId,
			WarningDeleteAllIds,
			WarningRemoveModifier,
			WarningRemovePreset,
			WarningRemoveCollection,
			WarningScriptFileNotFound,
			InfoLatestVersion,
			InfoUpdateAvailable,
			InfoRestartAviutl,
			CurveTypeNormal,
			CurveTypeValue,
			CurveTypeBezier,
			CurveTypeElastic,
			CurveTypeBounce,
			CurveTypeScript,
			CurveTypeLinear,
			ApplyModeNormal,
			ApplyModeIgnoreMidPoint,
			ApplyModeInterpolate,
			TooltipButtonApply,
			TooltipButtonCopy,
			TooltipButtonRead,
			TooltipButtonSave,
			TooltipButtonUnlocked,
			TooltipButtonLocked,
			TooltipButtonReset,
			TooltipButtonFit,
			TooltipButtonOthers,
			TooltipButtonIdBack,
			TooltipButtonIdNext,
			TooltipButtonIdNew,
			TooltipButtonCurrentId,
			TooltipButtonParam,
			TooltipButtonListConfig,
			TooltipButtonCollectionAdd,
			TooltipButtonCollectionEdit,
			TooltipButtonShowHandle,
			TooltipCreatedAt,
			ThemeSystem,
			ThemeDark,
			ThemeLight,
			PreferencesCategoryGeneral,
			PreferencesCategoryAppearance,
			PreferencesCategoryBehavior,
			PreferencesCategoryEditing,
			CaptionSelectBackgroundImage,
			CaptionSelectCurve,
			ModifierTypeDiscretization,
			ModifierTypeNoise,
			ModifierTypeSineWave,
			ModifierTypeSquareWave,
			SortByNone,
			SortByName,
			SortByDate,
			SortOrderAsc,
			SortOrderDesc,
			LabelCollectionOmitDate,
			LabelCollectionSetIndent,
			LabelLoading,
			LabelSearchPresets,
			LabelApplyDnD,
			LabelReset,
			LabelNoPresets,
			CollectionNameAll,
			CollectionNameDefault,
			CollectionNameUser,
			PromptPresetName,
			PromptCurveCode,
			PromptCurveParam,
			PromptCollectionName,
			CaptionPresetCreate,
			CaptionCurveCode,
			CaptionCurveParam,
			CaptionPresetRename,
			CaptionCollectionCreate,
			CaptionCollectionRename,
			CaptionCollectionImport,
			CaptionCollectionExport,
			WordVersion,
			WordEditMode,
			WordAutomatic,
			WordImageFile,
			WordSelect,
			WordCollection,
			WordCollectionFile,
			WordType,
			WordApply,
			WordOK,
			WordCancel,
			MenuEditorCurveAddAnchor,
			MenuEditorCurveReverse,
			MenuEditorCurveModifier,
			MenuEditorCurveCopy,
			MenuEditorCurvePaste,
			MenuEditorCurveAlignHandle,
			MenuEditorCurveShowScaleX,
			MenuEditorCurveShowScaleY,
			MenuEditorCurveShowHandle,
			MenuEditorCurveShowVelocityGraph,
			MenuEditorSegmentType,
			MenuEditorSegmentReverse,
			MenuEditorSegmentModifier,
			MenuOthersPanelLayout,
			MenuOthersPanelLayoutVertical,
			MenuOthersPanelLayoutHorizontal,
			MenuOthersExtension,
			MenuOthersExtensionManage,
			MenuOthersReloadUI,
			MenuOthersPreferences,
			MenuOthersHelp,
			MenuOthersAbout,
			MenuOthersNotificationUpdateAvailable,
			MenuPresetItemRename,
			MenuPresetItemRemove,
			MenuPresetSimpleView,
			MenuCollectionAddNew,
			MenuCollectionAddImport,
			MenuCollectionAddImportCecl,
			MenuCollectionAddImportFlow,
			MenuCollectionRename,
			MenuCollectionRemove,
			MenuCollectionExport,
			MenuEditorHandleBezierRoot,
			MenuEditorHandleBezierMatchAngle,
			MenuIDJumpToFirst,
			MenuIDJumpToLast,
			MenuIDDelete,
			MenuIDDeleteAll,
			NumStringId
		};

	private:
		static constexpr size_t MAX_LEN = 0x200;

		std::wstring string_data[(size_t)StringId::NumStringId];
	public:
		StringTable() noexcept;

		nlohmann::json create_json() const;

		const wchar_t* operator[] (StringId str_id);
	} string_table;
} // namespace curve_editor::global